### ISSUE TITLE
Error al ejecutar php app/console doctrine:fixtures:load

### ISSUE THREAD

**Issue by mvillagordo** [javiereguiluz/Cupon#119]
```
[Doctrine\ORM\ORMException]
  Entity of type Cupon\CiudadBundle\Entity\Ciudad is missing an assigned ID for field  'id'.
  The identifier generation strategy for this entity requires the ID field to be populated before
  EntityManager#persist() is called. If you want automatically generated identifiers instead
  you need to adjust the metadata mapping accordingly.
```

**Comment by rubenlb** [comment]
No pude cargar el fixture basico.php. tengo el siguiente error: 

PHP Catchable fatal error:  Argument 1 passed to Doctrine\Common\DataFixtures\Pu
rger\ORMPurger::__construct() must be an instance of Doctrine\ORM\EntityManagerI
nterface, instance of Doctrine\ORM\EntityManager given, called in G:\proyectos\c
upon2.3\vendor\doctrine\doctrine-fixtures-bundle\Doctrine\Bundle\FixturesBundle\
Command\LoadDataFixturesDoctrineCommand.php on line 100 and defined in G:\proyec
tos\cupon2.3\vendor\doctrine\data-fixtures\lib\Doctrine\Common\DataFixtures\Purg
er\ORMPurger.php on line 52
PHP Stack trace:
PHP   1. {main}() G:\proyectos\cupon2.3\app\console:0
PHP   2. Symfony\Component\Console\Application->run() G:\proyectos\cupon2.3\app\
console:27
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() G:\proyecto
s\cupon2.3\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:
121
PHP   4. Symfony\Component\Console\Application->doRun() G:\proyectos\cupon2.3\ve
ndor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:
96
PHP   5. Symfony\Component\Console\Application->doRunCommand() G:\proyectos\cupo
n2.3\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:191
PHP   6. Symfony\Component\Console\Command\Command->run() G:\proyectos\cupon2.3\
vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:900
PHP   7. Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand-
>execute() G:\proyectos\cupon2.3\vendor\symfony\symfony\src\Symfony\Component\Co
nsole\Command\Command.php:245
PHP   8. Doctrine\Common\DataFixtures\Purger\ORMPurger->__construct() G:\proyect
os\cupon2.3\vendor\doctrine\doctrine-fixtures-bundle\Doctrine\Bundle\FixturesBun
dle\Command\LoadDataFixturesDoctrineCommand.php:100

:(

**Comment by sebastianlp** [comment]
Para rubenlb y a los que les ocurra el mismo error:
Cambien en el composer.json el require del doctrine/orm. A mi me está funcionando con:
"doctrine/orm": ~2.2,>=2.2.3

Saludos

**Comment by rubenlb** [comment]
Gracias Sebastianlp pero persiste el preblema. ahora explico a detalle
1)	Tengo un Archivo de datos ciudades.php (solo 1) :
<?php
namespace Cupon\CiudadBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\Persistence\ObjectManager;
use Cupon\CiudadBundle\Entity\Ciudad;

/**
 * Fixtures de la entidad Ciudad.
 * Crea 25 ciudades para poder probar la aplicación.
 */
class Ciudades extends AbstractFixture
{

    public function load(ObjectManager $manager)
    {
        // Los 25 municipios más poblados de España según el INE
        // fuente: http://es.wikipedia.org/wiki/Municipios_de_Espa%C3%B1a_por_poblaci%C3%B3n

        $ciudades = array(
            'Madrid',
            'Barcelona',
            'Valencia',
            'Sevilla',
            'Zaragoza',
            'Málaga',
            'Murcia',
            'Palma de Mallorca',
            'Las Palmas de Gran Canaria'
        );

        foreach ($ciudades as $nombre) {
            $ciudad = new Ciudad();
            $ciudad->setNombre($nombre);

            $manager->persist($ciudad);
        }

        $manager->flush();
    }
}
2)	Configuración composer.json como recomendaste sebastianlp

"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.3.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "1.2.*",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.3.*",
        "symfony/swiftmailer-bundle": "2.3.*",
        "symfony/monolog-bundle": "2.3.*",
        "sensio/distribution-bundle": "2.3.*",
        "sensio/framework-extra-bundle": "2.3.*",
        "sensio/generator-bundle": "2.3.*",
        "incenteev/composer-parameter-handler": "~2.0",
        "doctrine/doctrine-fixtures-bundle": "dev-master",
        "doctrine/data-fixtures": "dev-master"

No tengo ningún otro datafixture en los demás bundles, pero al cargar con php app/console doctrine:fixtures:load sale ERROR:
PHP Catchable fatal error:  Argument 1 passed to Doctrine\Common\DataFixtures\Pu
rger\ORMPurger::__construct() must be an instance of Doctrine\ORM\EntityManagerI
nterface, instance of Doctrine\ORM\EntityManager given, called in G:\proyectos\c
upon2.3\vendor\doctrine\doctrine-fixtures-bundle\Doctrine\Bundle\FixturesBundle\
Command\LoadDataFixturesDoctrineCommand.php on line 100 and defined in G:\proyec
tos\cupon2.3\vendor\doctrine\data-fixtures\lib\Doctrine\Common\DataFixtures\Purg
er\ORMPurger.php on line 52

Espero ayuda con esto por favor.

**Comment by sebastianlp** [comment]
@rubenlb Hola, ejecutaste el comando composer update después de actualizar los require como los había puesto

**Comment by rubenlb** [comment]
Me equivoqué en una coma antes de composer update, y despues que corregí ya no lo actualize..... ¡FUNCIONA!...... gracias

**Comment by fcojaviergon** [comment]
This work for me: "doctrine/orm": "~2.2,>=2.2.3",
