### ISSUE TITLE
tres dudas

### ISSUE THREAD

**Issue by joaquinmgadea** [javiereguiluz/Cupon#135]
Saludos.

- Al bajarme la aplicación con git no aparecen las imágenes: he cambiado en 'cupon/app/config/config.yml', '/uploads/images/' por '/cupon/web/uploads/images/'
(Como estoy empezando no sé si es la forma más correcta; pero bueno, de momento se ven, pero no sé si se hace así).

- En la extranet, al crear una oferta sin poner ninguna foto me sale un error:
An exception occurred while executing 'INSERT INTO Oferta (nombre, slug, descripcion, condiciones, rutaFoto, precio, descuento, fecha_publicacion, fecha_expiracion, compras, umbral, revisada, ciudad_id, tienda_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["heggfeeh", "heggfeeh", "gfhfdhefhefhnfgngfngfkbkfgbklgfjblgkfjblkgfjlkbjlkgfjlkbjlkfgjbljfglkbjlkfgjlbjlfgjkjblkfgkjblkfgbj", "ghegfhffhe", null, 222, 22, null, null, 0, 22, 0, "11", 40]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'rutaFoto' cannot be null 

Al no haber foto, da ese error; he intentado cambiar en ¡src/Cupon/OfertaBundle/Form/Extranet/OfertaType.php', '->add('foto', 'file', array('required' => false))' por '->add('foto', 'file', array('required' => true))'; pero me sigue dando el problema. También he probado a cambiar en 'src/Cupon/OfertaBundle/Entity/Oferta.php' en la función 'subirFoto', pasando del código de github 'if (null === $this->getFoto()) {' por 
'if (null === $this->foto) {' 
Como estoy muy verde todavía, no veo cómo solucionarlo.

- Por último, he visto que el checkbox 'acepto' de añadir oferta, guarda la oferta tanto si está marcado como si no:
He cambiado en 'src/Cupon/OfertaBundle/Form/Extranet/OfertaType.php', '$builder->add('acepto', 'checkbox', array('mapped' => false, 'required' => false));' por '$builder->add('acepto', 'checkbox', array('mapped' => false, 'required' => true));'. Al no funcionar, no se me ocurre qué más hacer, dado mi nivel.

**Comment by davidnegreira** [comment]
Sobre el punto 1 de las imagenes creo que lo mas correcto seria poner:
**directorio_imagenes: 'uploads/images/'**

De esta forma las rutas son relativas y no tendras problemas de carga

**Comment by joaquinmgadea** [comment]
Gracias, David
