### ISSUE TITLE
Problemas con la traducción del contenido estático (Symfony 2.3 y Symfony 2.4)

### ISSUE THREAD

**Issue by jbvm** [javiereguiluz/Cupon#143]
Siguiendo el libro Symfony 2.4 (me pasaba lo mismo con Symfony 2.3) no me realiza las traducciones del contenido estático (El contenido dinámico todavía no lo he probado). Tengo el fichero OfertaBundle/Resources/translations/messages.en.xliff con el siguiente contenido:

*******************************************
<?xml version="1.0"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file source-language="es" datatype="plaintext" original="file.ext">
        <body>
            <trans-unit id="1">
                <source>Oferta del día</source>
                <target>Daily offer</target>
            </trans-unit>
            <trans-unit id="2">
                <source>Ofertas recientes</source>
                <target>Recent offers</target>
            </trans-unit>
            <trans-unit id="3">
                <source>Mis ofertas</source>
                <target>My offers</target>
            </trans-unit>
            <trans-unit id="4">
                <source>Comprar</source>
                <target>Buy now</target>
            </trans-unit>
            <trans-unit id="5">
                <source>Accede a tu cuenta</source>
                <target>Account login</target>
            </trans-unit>
            <trans-unit id="6">
                <source>Email</source>
                <target>Email</target>
            </trans-unit>
            <trans-unit id="7">
                <source>Contraseña</source>
                <target>Password</target>
            </trans-unit>
            <trans-unit id="8">
                <source>Entrar</source>
                <target>Login</target>
            </trans-unit>
            <trans-unit id="9">
                <source>No cerrar sesión</source>
                <target>Keep me logged in</target>
            </trans-unit>
            <trans-unit id="10">
                <source>Ayuda</source>
                <target>Help</target>
            </trans-unit>
            <trans-unit id="11">
                <source>Contacto</source>
                <target>Contact</target>
            </trans-unit>
            <trans-unit id="12">
                <source>Privacidad</source>
                <target>Privacy</target>
            </trans-unit>
            <trans-unit id="13">
                <source>Sobre nosotros</source>
                <target>About us</target>
            </trans-unit>
            <trans-unit id="14">
                <source>Regístrate</source>
                <target>Sign up</target>
            </trans-unit>
            <trans-unit id="15">
                <source>Regístrate ya</source>
                <target>Sign up now</target>
            </trans-unit>
            <trans-unit id="16">
                <source><![CDATA[<strong>Faltan</strong>: %tiempo%]]></source>
                <target><![CDATA[%tiempo% <strong>left</strong>]]></target>
            </trans-unit>
            <trans-unit id="17">
                <source><![CDATA[{1} ¡<strong>Una sola compra más</strong> <br/> activa la oferta!|[1, 9] ¡<strong>Sólo faltan %faltan% compras</strong> <br/> para activar la oferta!|]9,Inf] Faltan <strong>%faltan% compras</strong> <br/> para activar la oferta]]></source>
                <target><![CDATA[{1} <strong>Just one more purchase</strong> needed <br/> to get the deal!|[1, 9] <strong>Just %faltan% more</strong> needed <br/> to get the deal!|]9,Inf] <strong>%faltan% more</strong> needed <br/> to get the deal]]></target>
            </trans-unit>
            <trans-unit id="18">
                <source><![CDATA[<strong>Finalizada</strong> el %fecha%]]></source>
                <target><![CDATA[Expired on %fecha%]]></target>
            </trans-unit>
            <trans-unit id="19">
                <source>Finalizada el %fecha%</source>
                <target>Expired on %fecha%</target>
            </trans-unit>
            <trans-unit id="20">
                <source><![CDATA[<strong>Oferta activada</strong> por superar las <strong>%compras%</strong> compras necesarias]]></source>
                <target><![CDATA[<strong>The deal is on!</strong> More than <strong>%compras%</strong> purchased.]]></target>
            </trans-unit>
            <trans-unit id="21">
                <source>Comprada el %fecha%</source>
                <target>Bought on %fecha%</target>
            </trans-unit>
            <trans-unit id="22">
                <source>Compras</source>
                <target>Purchases</target>
            </trans-unit>
            <trans-unit id="23">
                <source>Condiciones</source>
                <target>Terms</target>
            </trans-unit>
            <trans-unit id="24">
                <source>Disfruta de la oferta en</source>
                <target>Enjoy this offer at</target>
            </trans-unit>
            <trans-unit id="25">
                <source>Sobre la tienda</source>
                <target>About the store</target>
            </trans-unit>
            <trans-unit id="26">
                <source>Ver mi perfil</source>
                <target>View/edit my profile</target>
            </trans-unit>
            <trans-unit id="27">
                <source>Cerrar sesión</source>
                <target>Log out</target>
            </trans-unit>
            <trans-unit id="28">
                <source>Regístrate gratis como usuario</source>
                <target>FREE sign up</target>
            </trans-unit>
            <trans-unit id="29">
                <source>Ofertas recientes en</source>
                <target>Recent offers at</target>
            </trans-unit>
            <trans-unit id="30">
                <source>Ofertas en otras ciudades</source>
                <target>Offers in other cities</target>
            </trans-unit>
            <trans-unit id="31">
                <source><![CDATA[<a href="%portada%">CUPON</a> publica cada día una oferta increíble en tu ciudad con descuentos de hasta el 90% <a class="boton" href="%registro%">Regístrate ya</a>]]></source>
                <target><![CDATA[<a href="%portada%">CUPON</a> publishes an amazing deal every day in your city with huge discounts of up to 90% <a class="boton" href="%registro%">sign up now</a>]]></target>
            </trans-unit>
        </body>
    </file>
</xliff>
*******************************************
Y por ejemplo el fichero app/Resources/views/frontend.html.twig con el siguiente contenido:

*******************************************
{% set ciudadSeleccionada = app.request.attributes.get('ciudad', ciudad_por_defecto) %}
{# las dos lineas anteriores son equivalentes la primera esta comentada #}
{% extends '::base.html.twig' %}
{% block stylesheets %}
{% stylesheets '@CuponOfertaBundle/Resources/public/css/normalizar.css' '@CuponOfertaBundle/Resources/public/css/comun.css' '@CuponOfertaBundle/Resources/public/css/frontend.css' output='css/frontend.css' %}
    <link href="{{ asset_url }}" rel="stylesheet" type="text/css" />
{% endstylesheets %}
{% endblock %}
{% block javascripts %}{% endblock %}

{% block body %}
<header>
    <h1><a href="{{path('portada', {'ciudad':ciudadSeleccionada})}}">CUPON</a></h1>
    <nav>
        <ul>
            <li><a href="{{path('portada', {'ciudad':ciudadSeleccionada})}}">{% trans %}Oferta del día{% endtrans %}</a></li>
            <li><a href="#">{{ "Ofertas recientes" | trans }}</a></li>
            <li><a href="#">{% trans %}Mis ofertas{% endtrans %}</a></li>
            
            <li>{{ render(controller('CuponCiudadBundle:Default:listaCiudades', { 'ciudad':ciudadSeleccionada })) }}</li>

        </ul>
    </nav>
</header>
 
<article>
    {% block article %}
        
    {% endblock %}
</article>
 
<aside>
    {% block aside %}
    <section id="login">
        {{ render_esi(controller('CuponUsuarioBundle:Default:cajaLogin')) }}
    </section>
    {% endblock %}
</aside>
{% endblock %}
*******************************************

Y no me coge ninguna de las palabras traducidas.
No se si me falta algo por hacer. Por favor, si me pueden echar una mano, gracias.

**Comment by frm666** [comment]
me ocurre lo mismo consigo la traduccion del contenido dinamico de bases de datos pero no el estatico...

cuando ejecuto el siguiente comando si me saca correctamente las traducciones....
>php app/console debug:traslation en AcmeHelloBundle

**Comment by frm666** [comment]
solucionado en mi caso habia añadido la clave translator en un nuevo campo framework. Tras subsanarlo funciono perfectamente trans
