### ISSUE TITLE
Login Extranet

### ISSUE THREAD

**Issue by luisctrujillo** [javiereguiluz/Cupon#145]
Buenas Tardes... realizo todos los pasos del libro, pero cuando intento hacer login como una tienda, me sale el siguiente error.

ContextErrorException: Notice: serialize() [function.serialize]: "id" returned as member variable from __sleep() but does not exist in C:\wamp\www\Symfony_Cupon\vendor\symfony\symfony\src\Symfony\Component\Security\Core\Authentication\Token\AbstractToken.php line 159

Gracias de antemano

**Comment by shubaivan** [comment]
I have this problem too
ContextErrorException: Notice: serialize(): &quot;id&quot; returned as member variable from __sleep() but does not exist in /var/www/artel-freelancedb/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php line 160
