### ISSUE TITLE
"No se puede encontrar driver" al ejecutar php app/console doctrine:schema:create

### ISSUE THREAD

**Issue by siverio** [javiereguiluz/Cupon#158]
Bueno, este es mi problema: al ejecutar este comando y tras configurar el parameters.yml, aparece lo siguente:
![seleccion_003](https://cloud.githubusercontent.com/assets/5946094/4343393/6f9bff10-4055-11e4-836c-d21e49be6ffb.png)
Ruego ayuda, estoy bastante verde en programación web. Muchas gracias.

**Comment by yeisonestiben** [comment]
hola me llamo estiben  soy de Colombia me a perece el mismo error  
parameters:
    database_driver: pdo_mysql
    database_path: 'mysql'
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: es
    secret: ThisTokenIsNotSoSecretChangeIt
y no se si en la configuracion
# Configuración de Doctrine
doctrine:
    dbal:
        driver:   %database_driver%
        charset:  UTF8
        # Si NO usas SQLite, comenta esta línea
        path:     "%database_path%"
        # Si usas MySQL, descomenta estas líneas
        # host:     %database_host%
        # port:     %database_port%
        # dbname:   %database_name%
        # user:     %database_user%
        # password: %database_password%
hay que des comentarla
 le agradecería  demasiado la verdad necesito aprender bastante  gracias
