### ISSUE TITLE
no funciona el login de la extranet

### ISSUE THREAD

**Issue by atamashi** [javiereguiluz/Cupon#162]
Hola Javier!le 
ante todo, mil gracias!

He instalado Cupon para symfony 2.5.x y todo corre bien en el frontend y la extranet, pero cuando voy al backend, creo una nueva tienda que he llamado prueba, le doy login prueba, password prueba, salt prueba y en fin lleno los demas datos, la grabo, la veo grabada al volver al listado, luego escribo en el navegador extranet y llego al formulario de login de la extranet, ingreso en el login prueba y el password prueba le doy clic a Entrar y no ingresa sino que me redirige al mismo formulario de login. No he tocado el codigo. Solo he usado la aplicacion recien instalada.

Gracias por tu ayuda, porque necesito desarrollar un backend completo en otro aplicativo.

Abrazos

**Comment by AntonMM** [comment]
Que dice el "log", algún error tiene dar.

**Comment by atamashi** [comment]
Por favor, Javier, disculpa mi tardanza en contestar.
El error que da en pantalla es bad credentials 
y analizando el log primero encuentra la ruta del login, 
luego va al listener situado en cupon oferta bundle,
busca la ciudad y va al login listener de usuario bundle, 
luego en la linea 69 dice que esta en el Security Context
y me ve como usuario anonimo y finalmente veo en la linea 246 
que chequea el login y falla la utenticacion de las credenciales 
redireccionandome al login de la extranet
Puedo enviarle los archivos completos de log 
y un zip con la historia del error en print screen
