### ISSUE TITLE
¿Como incluir cuadro de busqueda de ofertas que autocomplete?

### ISSUE THREAD

**Issue by rubenlb** [javiereguiluz/Cupon#165]
Muy buen aporte para la comunidad Symfony Javier!.... Felicidades!.
Mi inquietud es como se incluiría un cuadro de texto que autocomplete (como la busqueda de google) para la busqueda de ofertas? .Mi sugerencia sería que incluiyas esto a futuro en el tutorial Cupon.

**Comment by hborras** [comment]
No se si continuará desarrollando la aplicación de cupon más sobretodo desde que está en el equipo de Symfony. Además, es una demo introductoria y para otras cosas hay que investigar y ya.
