### ISSUE TITLE
 php app/console assetic:dump --env=prod marca errores en los paths

### ISSUE THREAD

**Issue by fhuizar** [javiereguiluz/Cupon#166]
al correr el comando  php app/console assetic:dump --env=prod me genera los siguientes errores

PHP Warning:  require_once(/home/francisco/Documents/repooncemore/Cupon/app/bootstrap.php.cache): failed to open stream: No such file or directory in /home/francisco/Documents/repooncemore/Cupon/app/console on line 10
PHP Stack trace:
PHP   1. {main}() /home/francisco/Documents/repooncemore/Cupon/app/console:0
PHP Fatal error:  require_once(): Failed opening required '/home/francisco/Documents/repooncemore/Cupon/app/bootstrap.php.cache' (include_path='.:/usr/local/php/php54/5.4.25/lib/php') in /home/francisco/Documents/repooncemore/Cupon/app/console on line 10
PHP Stack trace:
PHP   1. {main}() /home/francisco/Documents/repooncemore/Cupon/app/console:0

**Comment by hborras** [comment]
Buenas fhuizar. 

Parece que no tienes el archivo "bootstrap.php.cache" que debería estar en esta ruta:

/home/francisco/Documents/repooncemore/Cupon/app/bootstrap.php.cache
¿Puedes revisarlo?

Si ves que existe comprueba que tiene permisos de lectura (debería, pero por si acaso)

Un saludo

**Comment by fhuizar** [comment]
Hola javier, gracias por tu respuesta, haciendo pruebas resulto que eran
permisos en los logs, en otro tema, habra alguna documentación/libro que me
recomiendes leer sobre apache, no tengo conocimientos profundos al respecto

Gracias
Le 16 avr. 2015 02:11, "Hector Borras" <notifications@github.com> a écrit :

> Buenas fhuizar.
>
> Parece que no tienes el archivo "bootstrap.php.cache" que debería estar en
> esta ruta:
>
> /home/francisco/Documents/repooncemore/Cupon/app/bootstrap.php.cache
> ¿Puedes revisarlo?
>
> Si ves que existe comprueba que tiene permisos de lectura (debería, pero
> por si acaso)
>
> Un saludo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javiereguiluz/Cupon/issues/166#issuecomment-93662134>.
>

-- 
Linio, la tienda online más grande de Latinoamérica[image: Linio Mexico] 
<http://www.linio.com.mx/?wt_nl=mx.Newsletter.Postal.employee_signature.employee_signature&utm_source=Postal&utm_medium=CRM&utm_term=employee_signature_logo&utm_term=campana_employee_signature&utm_campaign=employee_signature>Compra 
más rápido y fácil. Descarga nuestra app[image: appstore] 
<https://app.adjust.io/uw4e8i_uu9f3u?campaign=MEX_SignatureMail&deep_link=linio%3A%2F%2Fmx&fallback=https%3A%2F%2Fitunes.apple.com%2Fmx%2Fapp%2Flinio%2Fid885989000%3Fmt%3D8>[image: 
googleplay] 
<https://app.adjust.io/uw4e8i_uu9f3u?campaign=MEX_SignatureMail&deep_link=linio%3A%2F%2Fmx&fallback=httpS%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.linio.android%26hl%3Des>Descubre 
nuestras promociones:[image: promociones] 
<http://www.linio.com.mx/transactional-email/?utm_source=CRM&utm_medium=employee_signature>

-- 


*This e-mail and any attachment contains information which is private and 
confidential and is intended for the addressee only. If you are not an 
addressee, you are not authorized to read, copy or use the e-mail or any 
attachment. If you have received this e-mail in error, please notify the 
sender by return e-mail and then destroy it.*

 

*El presente documento electrónico y cualquier anexo al mismo, contiene 
información confidencial y exclusiva para el destinatario. Si usted no es 
el destinatario, no está autorizado a leer este documento, a copiarlo o 
usar el presente y sus anexos o bien si usted ha recibido este documento 
electrónico por error, favor de notificar al remitente por este mismo 
conducto y proceda a eliminar de cualquier archivo este documento 
electrónico.*
