### ISSUE TITLE
Error en boton comprar en la parte de producción (app.php)

### ISSUE THREAD

**Issue by kratosps2** [javiereguiluz/Cupon#167]
Tengo toda la aplicación en apache2. Resulta que cuando le doy a comprar un producto ya comprado da un error. En el entorno de desarrollo funciona (app_dev.php) y muestra el error en la pantalla. Sin embargo en app.php no hace nada porque la capa esta oculta y parece que ha fallado no ocurriendo nada. Debería también mostrar el error no?

Muchimas gracias ( ojala hubiera muchos proyectos tecnologicos tan buenos como el tuyo ....)

**Comment by hborras** [comment]
Parecerá una tontería, pero has probado a borrar la caché? El entorno de producción no borra cacé por defecto.

Un saludo.

**Comment by kratosps2** [comment]
Sí, es el primer problema que tuve.Procedo a borrar la carpeta cache
"Cupon/app/cache/" manualmente. Hay que borrar mas?.
 Por lo que veo en app.php no aparece la capa de accede a tu cuenta, el div
encima de "Sobre nosotros" está oculto, mientras que en app_dev.php no.

Tengo comprado el libro de javier y estoy investigando.

Quedo a la espera de vuestra ayuda.

Muchísimas gracias..



2015-04-30 8:45 GMT+02:00 Hector Borras <notifications@github.com>:

**Comment by hborras** [comment]
No borres la carpeta "cache" en sí, borra el contenido, sino puede que luego tengas problemas de permisos. 

Por otro lado, creo que lo mejor es que nos pases un log de lo que ha pasado en la petición de app.php ( lo puedes encontrar en el profiler ). Incluso una captura de pantalla creo que estaría también bien para ver lo que comentas, porque no lo he entendido muy bien.

Un saludo.

**Comment by kratosps2** [comment]
Buenas,

Adjunto pantalla con app_dev y con app. Son casi iguales excepto el marco
de la derecha.

Que ocurre?  Si compro algo ya comprado en la primera aparece el error, sin
embargo en la de app no . Además no pone el usuario conectado.

Adjunto el error en el fichero de prod.(supongo que se puede activar mas
traza en este entorno...)


[2015-04-30 09:32:16] request.INFO: Matched route "portada" (parameters:
"_controller":
"Cupon\OfertaBundle\Controller\DefaultController::portadaAction", "ciudad":
"vitoria-gasteiz", "_locale": "es", "_route": "portada") [] []
[2015-04-30 09:32:16] security.DEBUG: Read SecurityContext from the session
[] []
[2015-04-30 09:32:16] security.DEBUG: Reloading user from user provider. []
[]
[2015-04-30 09:32:16] security.DEBUG: Username "usuario1@localhost" was
reloaded from user provider. [] []
[2015-04-30 09:32:16] security.DEBUG: Write SecurityContext in the session
[] []
[2015-04-30 09:32:16] request.ERROR: Uncaught PHP Exception
Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route
found for "GET /_fragment" (from "http://localhost/app.php/es/usuario/login")"
at /home/proyectos/Cupon/app/cache/prod/classes.php line 1980
{"exception":"[object]
(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route
found for \"GET /_fragment\" (from \"
http://localhost/app.php/es/usuario/login\") at
/home/proyectos/Cupon/app/cache/prod/classes.php:1980,
Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at
/home/proyectos/Cupon/app/cache/prod/appProdUrlMatcher.php:435)"} []
[2015-04-30 09:32:16] security.DEBUG: Write SecurityContext in the session
[] []
[2015-04-30 09:32:21] request.ERROR: Uncaught PHP Exception
Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route
found for "GET /_fragment" (from "
http://localhost/app.php/es/vitoria-gasteiz")" at
/home/proyectos/Cupon/app/cache/prod/classes.php line 1980
{"exception":"[object]
(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route
found for \"GET /_fragment\" (from \"
http://localhost/app.php/es/vitoria-gasteiz\") at
/home/proyectos/Cupon/app/cache/prod/classes.php:1980,
Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at
/home/proyectos/Cupon/app/cache/prod/appProdUrlMatcher.php:435)"} []


Muchas gracias
