### ISSUE TITLE
Error con composer update

### ISSUE THREAD

**Issue by fonson** [javiereguiluz/Cupon#169]
Felicidades por el libro.
No tengo ni idea de synfony.

He instalado la aplicación según el readme.com sin problemas.
Cuando ejecuto 'composer update' me da el siguiente error:

     Loading composer repositories with package information
     Updating dependencies (including require-dev)
     Your requirements could not be resolved to an installable set of packages.

     Problem 1
        - ideup/simple-paginator-bundle dev-master requires beberlei/doctrineextensions 0.3.0 -> no     matching package found.
    - ideup/simple-paginator-bundle dev-master requires beberlei/doctrineextensions 0.3.0 -> no matching package found.
    - Installation request for ideup/simple-paginator-bundle dev-master -> satisfiable by ideup/simple-paginator-bundle[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

He editado mi composer.json cambiando:

	"minimum-stability": "stable" por "minimum-stability": "dev"

Sigue dando el mismo error.

No se si tiene que ver pero los listados en backend el paginado se quedan a 1pagina
es mas en usuarios solo lista 6 cuando tengo 200.

Entrono:
MySQL Workbench Community (GPL) for Linux/Unix version 6.3.3  revision 0 build 592 (64 bit)
Cairo Version: 1.13.1
OS: Linux 3.13.0-63-generic
Distribution: Ubuntu 14.04.3 LTS

Gracias

**Comment by danieldacorte55** [comment]
this error is pretty simple. the error itself tells you what to do. you have to change in composer.json the beberlei/doctrineextensions version
default is "dev-master" you have to change it to "0.3.0" and run composer update again
it works
