### ISSUE TITLE
Error Cuenta Atras

### ISSUE THREAD

**Issue by estonomola** [javiereguiluz/Cupon#170]
Una vez realizada la clase CuponExtension.php  cuando voy por ejemplo a ver la oferta /madrid/ofertas/oferta-13-lorem-ipsum-dolor-sit-amet

En lugar de salirme la cuenta atrás me sale el código javascript en texto 

La función la he copiado de la última versión del libro (estoy siguiéndolo vía web)
 
¿Alguien puede ayudarme a ver cual es el problema?

Gracias

**Comment by GasGTI** [comment]
¿Podrías mostrar la función para ver si localizo el error?
Yo hice ese capitulo hace algunos días y me funciono correctamente.

**Comment by estonomola** [comment]
Hola @GasGTI, soy nuevo en github y no se porque en la Preview del comentario no me aparece el código de la función entero, no obstante la función cuentaAtras esta copiada de http://symfony.es/libro/leer/2.4/capitulo-7.html

	public function cuentaAtras($fecha)
    {
        $fecha = $fecha->format('Y,')
                 .($fecha->format('m')-1)
                 .$fecha->format(',d,H,i,s');
 
        $html = <<<EOJ
<script type="text/javascript">
function muestraCuentaAtras(){
    var horas, minutos, segundos;
    var ahora = new Date();
    var fechaExpiracion = new Date($fecha);
    var falta = Math.floor( (fechaExpiracion.getTime() - ahora.getTime()) / 1000 );
 
    if (falta < 0) {
        cuentaAtras = '-';
    }
    else {
        horas = Math.floor(falta/3600);
        falta = falta % 3600;
 
        minutos = Math.floor(falta/60);
        falta = falta % 60;
 
        segundos = Math.floor(falta);
 
        cuentaAtras = (horas < 10    ? '0' + horas    : horas)    + 'h '
                    + (minutos < 10  ? '0' + minutos  : minutos)  + 'm '
                    + (segundos < 10 ? '0' + segundos : segundos) + 's ';
 
        setTimeout('muestraCuentaAtras()', 1000);
    }
 
document.getElementById('tiempo').innerHTML = '<strong>Faltan:</strong> ' + cuentaAtras;
}
 
muestraCuentaAtras();
</script>
EOJ;
 
        return $html;
    }



Gracias.

**Comment by GasGTI** [comment]
Mirando tu código no veo nada que parezca estar mal, recuerdo que la etiqueta de cierre de EOJ daba problemas si tenia algún espacio o tabulador delante, pero parece que ese no es tu caso.

Revisando el resto de código que gestiona la cuenta atrás en mi proyecto, en la function getFilters() yo no uso el filtro "Twig_Filter_Method" por estar ya en desuso, en su defecto uso el "Twig_SimpleFilter".  

- Según el libro seria así:
public function getFilters()
    {
         return array(
             'mostrar_como_lista' => new \Twig_Filter_Method($this, 'mostrarComoLista', array('is_safe' => array('html'))),
             'cuenta_atras' => new \Twig_Filter_Method($this, 'cuentaAtras', array('is_safe' => array('html'))),
         );
    }

- Yo lo he puesto así:
public function getFilters()
    {
        return array(
            new \Twig_SimpleFilter('mostrar_como_lista', array($this, 'mostrarComoLista'), array('is_safe' => array('html'))),
            new \Twig_SimpleFilter('cuenta_atras', array($this, 'cuentaAtras'), array('is_safe' => array('html'))),
        );
    }


Creo que tu error puede venir en ese código y más concretamente en el is_safe ya que se usa para escapar cuando generas codigo HTML o javascript como es el caso.

Escapando automáticamente
Si está habilitado el escape automático, puedes escapar la salida del filtro antes de imprimir. Si tu filtro actúa como un escapista (o explícitamente produce código html o javascript), desearás que se imprima la salida sin procesar. En tal caso, establece la opción is_safe:

A ver si te ayuda algo ;)

**Comment by GasGTI** [comment]
Según el libro la función que se usa para generar los descuentos (Twig_Function_Method) también esta en desuso, es su defecto deberías usar Twig_SimpleFunctions.

Un saludo

**Comment by estonomola** [comment]
Muchísimas Gracias @GasGTI he cambiado la función getFilters() a como la tienes tu y ya funciona la cuenta atrás perfectamente.
