### ISSUE TITLE
problema al ejecutar:  php app/console doctrine:schema:create (siguiendo el Capitulo 5)

### ISSUE THREAD

**Issue by crashon182** [javiereguiluz/Cupon#171]
Hola me esta dando el siguiente error al tratar de crear un schema. La base de datos la puede crear correctamente, asi como las entidades, pero al ejecutar en consola el comando para crear el schema me tira el siguiente error.

PHP Fatal error:  Cannot redeclare class Doctrine\ORM\Mapping\ManyToOne in /home/crashon182/Escritorio/Proyectos/cupon/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ManyToOne.php on line 26

estoy usando ubuntu 15.10

alguien sabe que puede ocurrir? saludos!

**Comment by yeiij** [comment]
Parece que tienes una linea duplicada, sin código es difícil.

**Comment by crashon182** [comment]
lo solucione copiando los archivos del proyecto finalizado, lamentablemente no se en que entidad estaba el problema ni porque ocurria esto (los archivos temporales los habia borrado, porque en la documentación decia que ese podia se uno de los problemas. Gracias Yeii por tratar de ayudar igualmente!! saludos!
