### ISSUE TITLE
Error al intentar acceder a la aplicación

### ISSUE THREAD

**Issue by HexenZ** [javiereguiluz/Cupon#173]
Buenas, al intentar acceder a la aplicación recibo el siguiente mensaje:

An exception has been thrown during the rendering of a template ("The Symfony\Component\Intl\DateFormatter\IntlDateFormatter::__construct() method's argument $locale value 'es' behavior is not implemented. Only the locale "en" is supported. Please install the "intl" extension for full localization capabilities.") in OfertaBundle:Default:includes/oferta.html.twig at line 46.

**Comment by hborras** [comment]
Hola HexenZ, 

Lo que tienes que hacer es instalar la intl extension de php para poder hacer uso del IntlDateFormater. 

No se si estás usando windows o linux.

Si es linux, debes:

`sudo apt-get install php5-intl
`
You then need to restart Apache
`
sudo service apache2 restart
`
You can also check what extensions are compiled in by running:
`
php -m
`

**Comment by HexenZ** [comment]
Hecho! Muchas gracias Hector! :)
