### ISSUE TITLE
problemas con variables de js y twig

### ISSUE THREAD

**Issue by EduardoWorking** [javiereguiluz/Cupon#37]
Hola Javier, estoy siguiendo el libro al pie de la letra (o eso creo), y creando la lista de ciudades con el codigo que aparece en el libro:
&lt;select id=&quot;ciudadseleccionada&quot;&gt;
    {% for ciudad in ciudades %}
    &lt;option value=&quot;{{ ciudad.slug }}&quot;&gt;{{ ciudad.nombre }}&lt;/option&gt;
    {% endfor %}
&lt;/select&gt;

&lt;script type=&quot;text/javascript&quot;&gt;

```
var lista = document.getElementById("ciudadseleccionada");
var ciudad = lista.options[lista.selectedIndex].value;

lista.onchange = function() {
    var url = {{ path(&#039;portada&#039;, { &#039;ciudad&#039;:ciudad }) }};
};
```

&lt;/script&gt;
Recibo constantemente el error de que ciudad no existe en la linea 13, esta claro que es algun fallo de compatibilidad con twig, que no reconoce la variable, pero no se que hacer para arreglarlo. He hecho todas las pruebas que se me han pasado por la cabeza pero no ha habido forma.
Espero una respuesta, a nadie mas que siga el libro le ha pasado esto???

Muchas gracias de antemano.
PD: tampoco he sabido poner el codigo para que no se interprete, y lo he intentado

**Comment by SoyEva** [comment]
Hola,

Bueno, yo estoy empezando con Symfony y siguiendo el manual para hacer mi proyecto de fin de DAW. Se agradece mucho el libro, la verdad. Han pasado 5 años desde la última respuesta y no sé si habrá alguien por aquí.
El caso es que yo he conseguido hacer que funcione sin problema el option y dirige a la página de cada ciudad. Lo que me gustaría saber es cómo enviar los datos al darle a un botón de enviar y no cuando se selecciona la opción.

Necesito hacer esto porque quiero añadir otra campo, un <input type="radio"...> Es decir, que al darle a enviar pueda pasar la ciudad seleccionada y otro valor como variables a una ruta.

He intentado con twig, que tampoco lo controlo demasiado y con JS y no he sido capaz, a ver si alguien me da una idea. Gracias.

**Comment by blackatze93** [comment]
Puedes agregarle el botón dentro del select y con Javascript ejecutar la acción al oprimir el botón.  Si dejaras lo que tienes hecho te podría ayudar mejor.

**Comment by SoyEva** [comment]
Muchas gracias por responder.
Eso es lo que he intentado pero no he conseguido que funcione. 

```
<select id="ciudadSeleccionada">
	{% for ciudad in ciudades %}
		<option 
		data-url="{{ url('portada_filtro', { 'ciudad': ciudad.slug }) }}">
		{{ ciudad.nombre }}
		</option>
	{% endfor %}
  	<input id="boton" type="submit">
</select>
<script type="text/javascript">
	var enviar = document.getElementById('boton');
	enviar.onclick = function() {
	var url = enviar.options[enviar.selectedIndex].getAttribute('data-url');
	window.location = url;
	};
</script>
```

Obviamente algo estoy haciendo mal...

**Comment by SoyEva** [comment]
Ya lo tengo. Era una chorrada :-)

```
<script type="text/javascript">
	var boton = document.getElementById('boton');
	var enviar = document.getElementById('ciudadSeleccionada');
	boton.onclick = function() {
	var url = enviar.options[enviar.selectedIndex].getAttribute('data-url');
	window.location = url;
	};
</script>
```
