### ISSUE TITLE
RuntimeException: Failed to write cache file "/var/www/cupon/app/cache/dev/classes.php

### ISSUE THREAD

**Issue by snakewarm** [javiereguiluz/Cupon#50]
saludos Javier 
Recien me estoy iniciando en el mundo de symfony
Y te agradezco en colgar este aplicativo para el aprendizaje de todos
pero tengo este problema
RuntimeException: Failed to write cache file "/var/www/cupon/app/cache/dev/classes.php".
1. in /var/www/cupon/app/bootstrap.php.cache line 1079
2. at ClassCollectionLoader::writeCacheFile() in /var/www/cupon/app/bootstrap.php.cache line 1017
3. at ClassCollectionLoader::load() in /var/www/cupon/app/bootstrap.php.cache line 682
4. at Kernel->loadClassCache() in /var/www/cupon/web/app_dev.php line 21

Todo esto lo estoy haciendo desde ubuntu

agradesco por la ayuda

**Comment by damesad** [comment]
Es problema de permisos , lo puede solucionar siguiendo esta guia en expañol.

[www.symfony.es/documentacion/permisos](http://symfony.es/documentacion/como-solucionar-el-problema-de-los-permisos-de-symfony2/)
