### ISSUE TITLE
Problema al instalar Composer [SOLUCIONADO]

### ISSUE THREAD

**Issue by eduardobape** [javiereguiluz/Cupon#72]
Hola a todos. Acabo de comprar el libro de Symfony de Javier Eguiluz, y nada más empezar ya tengo un problema. El problema tiene que ver con la instalación de Composer en Windows 7.

Sigo correctamente todos los pasos del punto 3.1.1.1 del capítulo 3 del libro hasta que llego al paso donde dice:

Después de todos estos pasos, abre una nueva consola de comandos y ejecuta el siguiente comando sin ninguna opción:

C:> composer

Lo ejecuto y obtengo el siguiente mensaje:

Could not open input file: composer.phar

En cambio, si me muevo en la consola de comandos al directorio donde tengo los archivos composer.phar y composer.bat, es decir, al directorio D:\xampp\php (tengo instalado xampp) y ejecuto desde éste el siguiente comando:

composer -V

obtengo la salida: 

Composer version 0e0af00

Sé que para Windows existe un instalador .exe para Composer, pero mi cabezonería hace que quiera resolver la instalación manual y global de Composer por mí mismo desde la consola de comandos.

Espero que alguien me ayude pues sin instalar composer no puedo seguir con la instalación de Symfony que recomienda el libro.

**Comment by gullitmoran** [comment]
hola no he podido instalar composer no se porque me aparece esto:

Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
The download failed repeatedly, aborting.

si alguien me puede ayudar por favor

**Comment by gullitmoran** [comment]
me descargo el instalador  Composer-Setup.exe lo ejecuto, busco la direccion donde se encuentra php.exe entonces cuando le doy instalar me aparece lo que le escribi en el mensaje anterior 

Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
The download failed repeatedly, aborting.

si alguien me puede ayudar se lo agradeceria

**Comment by AntonMM** [comment]
Descarga fallida, prueba a descargarlo manualmente poniendo la direccion en el navegador, tambien puedes probar a descargar el certificado por si te puede servir de ayuda.

Y comprueba que tengas instalado SSL en tu maquina.

Un saludo.

**Comment by matyaslp** [comment]
Me estaba pasando exactamente lo mismo, Muchas gracias Eduardobape!

**Comment by GuzmanT** [comment]
este es lo que campio ...soy novato
php "${dir}/composer.phar" $*

**Comment by thavoo** [comment]
Buenas noches. Alguien a instalado el Laravel/Composer en debian jessie??' es que me ha dado ciertos problemas. Saludos

**Comment by facunq** [comment]
Gracias eduardobape por la solución.

**Comment by jorgeale90** [comment]
Hola a todos, tengo un problema al instalar el composer en mi computadora de sistema operativo Windows 10, este es el error:
----------------------------------------------------------------------------------------------
The Composer installer script was not successful [exit code 1].

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
-------------------------------------------------------------------------------------------------
Me conecto a internet por mediante un proxy, le doy la url del proxy y aun me sigue saliendo el mismo error, si alguien me puede ayudar...Gracias

**Comment by CARLOS-BARAJAS** [comment]
me salia el mismo error solo pon el http de tu proxy y el puerto ejemplo 192.168.1.1:3121 al momento de instalar composer
