### ISSUE TITLE
Problema al ejecutar "php app/console". Siempre ejecuta mismo comando.

### ISSUE THREAD

**Issue by submarinu** [javiereguiluz/Cupon#82]
Hola Javier,

He creado un proyecto desde cero en paralelo a tu proyecto Cupon y me ha pasado antes que nunca antes me había pasado con Symfony (estoy con la 2.2).

Creé el primer bundle y a partir de ahora, cualquier comando que ejecuto utilizando "php app/console" me saca el mismo error. Es decir es como si siempre me ejecutase el comando de la ejecución de la creación del primer bundle que he creado:

Es decir, la creación del primer bundle perfecta. Pero a partir de ahí, ponga lo que ponga, me sale siempre lo mismo:

Caso 1:

```
C:\Project\CuponLocal>php app/console create:bundle

  [LogicException]
  Trying to register two bundles with the same name "OfertaBundle"
```

Caso 2:

```
C:\Project\CuponLocal>php app/console clear:cache

  [LogicException]
  Trying to register two bundles with the same name "OfertaBundle"
```

Caso 2:

```
C:\Project\CuponLocal>php app/console aaaaaaaaaaaaaaa

  [LogicException]
  Trying to register two bundles with the same name "OfertaBundle"
```

Hay algún tipo de caché en el `app/console`??? Me estoy volviendo loco.

**Comment by MaskeZen** [comment]
Se que es viejo pero llegué acá intentando solucionar el problema en un symfony 2.4.

En el caso de que hablo el error estaba en que se agregaba el bundle dos veces en el appkernel.
